

CREATE TABLE [dbo].[MapUserCompanyGroup](
	[MapUserCompanyGroupId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NULL,
	[CompanyGroupId] [bigint] NULL,
 CONSTRAINT [PK_MapUserCompanyGroup] PRIMARY KEY CLUSTERED 
(
	[MapUserCompanyGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


